version: 2.1
orbs:
  node: circleci/node@5.0.2
  coveralls: coveralls/coveralls@2.2.5

jobs:
  build_and_test: # this can be any name you choose
    docker:
      - image: cimg/node:20.11.1
        environment:
          DATABASE_HOST: 0.0.0.0
          DATABASE_PORT: 5432
          DATABASE_USER: postgres
          DATABASE_PASSWORD: postgres
          DATABASE_NAME: usersdb_test
          DATABASE_SYNC: true
          POKEMON_API_URL: https://pokeapi.co/api/v2
          COVERALLS_REPO_TOKEN=gLskLgZ58OYgHYPem2MLSnox65zICVe8t
      # Service container image
      - image: cimg/postgres:15.0
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: usersdb_test
    executor: node/default # use the default executor defined within the orb
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run test:e2e
          name: Run tests
      - run:
          command: npm run build
          name: Install and Make
      - persist_to_workspace:
          root: ~/project
          paths: .
workflows:
  build_test_deploy: # this can be any name you choose
    jobs:
      - build_and_test
